language: python
sudo: required


python:
  - '3.6'

install:
    - pip install --upgrade setuptools
    - pip install codecov
    - pip install -r requirements-dev.txt
    - pip install -e .

script:
    make cov
after_success:
    codecov
