language: python
sudo: required


python:
  - '3.6'

install:
    - pip install --upgrade setuptools
    - pip install codecov
    - pip -r requirements-dev.txt
    - pip install -e .
    - make cov

script:
    make cov
after_success:
    codecov
